OE4T/tegra-demo-distro

.gitmodules
layers/meta-tegrademo/classes/mender-workarounds.bbclass
layers/meta-tegrademo/conf/distro/tegrademo-mender.conf
layers/meta-tegrademo/conf/distro/tegrademo.conf
layers/meta-tegrademo/conf/template-tegrademo-mender/bblayers.conf.sample
layers/meta-tegrademo/conf/template-tegrademo-mender/conf-notes.txt
layers/meta-tegrademo/conf/template-tegrademo-mender/local.conf.sample

This adds support for mender in a distro named 'tegrademo-mender'

Master+tegrademo mender

---

layers/meta-tegrademo/conf/template-tegrademo-mender/local.conf.sample

As discussed in https://github.com/OE4T/meta-tegra/issues/475#issuecomment-721873550

Fix comment line for NVIDIA_DEVNET_MIRROR

---

layers/meta-tegrademo/conf/template-tegrademo/local.conf.sample

See discussion at https://github.com/OE4T/meta-tegra/issues/475#issuecomment-734889646
I missed this one with https://github.com/OE4T/tegra-demo-distro/commit/7ff44ca1848430a6a8ac1afeb401a9dcede40ab2
Signed-off-by: Dan Walkes <danwalkes@boulderai.com>

Fix comment in local.conf.sample

---

README.md
layers/meta-tegra-support/conf/layer.conf
layers/meta-tegra-support/dynamic-layers/meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bbappend
layers/meta-tegrademo/classes/mender-workarounds.bbclass
layers/meta-tegrademo/conf/template-tegrademo/local.conf.sample
scripts-setup/git-scripts/prepare-commit-msg
scripts-setup/setup-git-hooks

* Updates all of the submodules to the latest on their respective branches
* Adds some workarounds to clean up some build issues with the latest meta-mender-core and meta-mender-tegra

Layer updates for dunfell-l4t-r32.4.3

---

layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-nano-emmc/flash_mender.xml
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-nano-qspi-sd/flash_mender.xml
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/tegra210/flash_mender.xml
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout_%.bbappend
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/libubootenv_%.bbappend

Completes some missing changes from #19

Layer updates for gatesgarth - part 2

---

.gitmodules
layers/meta-tegra-support/conf/layer.conf
layers/meta-tegra-support/dynamic-layers/meta-mender-core/recipes-mender/mender-artifact/mender-artifact_%.bbappend
layers/meta-tegra-support/dynamic-layers/meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bbappend
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-nano-emmc/flash_mender.xml
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-nano-qspi-sd/flash_mender.xml
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/tegra210/flash_mender.xml
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout_%.bbappend
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/libubootenv_%.bbappend
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0003-Integration-of-Mender-boot-code-into-U-Boot.patch
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0010-tegra-mender-auto-configured-modified.patch
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0011-Jetson-TX2-mender-boot-commands.patch
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0012-p3541-0000_defconfig-Mender-patch.patch
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0013-Reduce-env-size-on-p3450-0000-to-64KiB.patch
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0015-Update-TX1-nano-emmc-defconfigs-for-new-UBENV-locati.patch
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_2020.10.bbappend
layers/meta-tegrademo/classes/mender-workarounds.bbclass
layers/meta-tegrademo/conf/distro/tegrademo-mender.conf
layers/meta-tegrademo/conf/distro/tegrademo.conf
layers/meta-tegrademo/conf/template-tegrademo-mender/bblayers.conf.sample

* Switches poky to master branch
* Switches meta-mender and meta-mender-community to dunfell branch in each, since that's more stable
* Adds updated patches for u-boot-tegra for Mender for v2020.10
* Ported in other fixes and workarounds from gatesgarth

Updates for master

---

layers/meta-tegra-support/recipes-devtools/vpi/vpi1-samples/0001-06-klt_tracker-minor-update-in-usage.patch
layers/meta-tegra-support/recipes-devtools/vpi/vpi1-samples/CMakeLists.txt
layers/meta-tegra-support/recipes-devtools/vpi/vpi1-samples_1.0.15.bb

Add recipe to build and install VPI sample applications.

vpi1-samples: add recipe

---

layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-xavier-nx-devkit-tx2-nx/flash_mender.xml
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0017-Jetson-Xavier-NX-TX2-NX-mender.patch
layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_2020.04.bbappend
layers/meta-tegra-support/recipes-test/tegra-tests/gstreamer-tests/confvars.in
layers/meta-tegra-support/recipes-test/tegra-tests/gstreamer-tests/sinteltest.sh.in

* Update meta-tegra to pick up L4T R32.5.1 additions for the TX2-NX module
* Back-port updates from master with the updates to add Mender support for TX2-NX

Update with TX2-NX support

---

layers/meta-tegrademo/conf/distro/tegrademo.conf

distro/tegrademo.conf: update DISTRO_CODENAME

---

layers/meta-tegrademo/conf/template-tegrademo-mender/conf-notes.txt
layers/meta-tegrademo/conf/template-tegrademo/conf-notes.txt
layers/meta-tegrademo/recipes-demo/images/demo-image-full.bb

demo-image-full: add vpi1-samples

---

README.md

README.md: minor update to be consistent with meta-tegra wiki page.

---

layers/meta-tegra-support/recipes-test/tegra-tests/gstreamer-tests/capturetest.sh.in

gstreamer-tests: fix capturetest script issue

---

layers/meta-tegra-support/recipes-test/tegra-tests/vpi1-tests/run-vpi1-tests.sh
layers/meta-tegra-support/recipes-test/tegra-tests/vpi1-tests_1.0.bb
layers/meta-tegrademo/recipes-demo/images/demo-image-full.bb

for automating test runs of the VPI samples.

meta-tegra-support: add vpi1-tests recipe

---

layers/meta-tegrademo/conf/template-tegrademo-mender/conf-notes.txt
layers/meta-tegrademo/conf/template-tegrademo/conf-notes.txt
layers/meta-tegrademo/recipes-demo/images/demo-image-full.bb

which will pull in tensorrt-samples

demo-image-full: add tensorrt-tests to image

---

layers/meta-tegrademo/recipes-demo/images/demo-image-full.bb

demo-image-full: drop libvisionworks-devso-symlink

---

layers/meta-tegrademo/recipes-demo/images/demo-image-full.bb

demo-image-full: fix typo

---

layers/meta-tegrademo/scripts/setup-udev-rules

setup-udev-rules: add jetson-orin-agx-devkit support

---

layers/meta-tegrademo/recipes-demo/images/demo-image-full.bb

which will pull in vpi2-samples

demo-image-full: replace vpi1-tests by vpi2-tests

---

layers/meta-tegrademo/recipes-demo/packagegroups/packagegroup-demo-egltests.bb

packagegroup-demo-egltests: drop obsolete package

---

.gitmodules

To move dynamic layer content from meta-tegra-community upstream.
See thread at [1]
1: https://gitter.im/OE4T/jetpack-4.6.3-test?at=638baf151bcd2b707870897a
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>

repos: update meta-mender-community meta-tegra-community
