OE4T/tegra-demo-distro

- layers/meta-tegra-support/conf/layer.conf
- layers/meta-tegra-support/dynamic-layers/meta-mender-core/recipes-kernel/linux/linux-tegra_%.bbappend
- layers/meta-tegra-support/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
- layers/meta-tegra-support/recipes-core/images/tegra-minimal-initramfs.bbappend
- layers/meta-tegrademo/classes/mender-workarounds.bbclass
The changes here, combined with the meta-mender-tegra fixes in [this PR](https://github.com/OE4T/meta-mender-community/pull/2) are most, if not all, of the fixes and workarounds I've added to [my forked test distro](https://github.com/madisongh/tegra-test-distro) after running through multiple automated builds of the demo images on all of the tegra platforms with for both mender and non-mender cases.
Some are simple, and some required tracking down well-buried task hash changes that were preventing reuse of shared state, either between builds of the same flavor, or builds between mender and non-mender.
> Updates and fixes

- layers/meta-tegrademo/recipes-demo/images/demo-image-full.bb
since the Deepstream 5 Docker container needs CUDA
libraries not already pulled in by other packages.
> demo-image-full: add cuda-libraries

- layers/meta-tegrademo/recipes-core/base-files/base-files_%.bbappend
For tegrademo-mender builds, we add overlay mounts
to fstab, so add the overlay module as a runtime
recommendation.
> base-files: add RRECOMMENDS on kernel-module-overlay

- README.md
- scripts-setup/git-scripts/prepare-commit-msg
- scripts-setup/setup-git-hooks
Per discussion in the monthly meeting, add a contributor guide and update the README.
Add a pre-commit hook setup script for automated git signoff to correspond to contributor guide requirements.
See work in progress [contributor guide wiki page](https://github.com/OE4T/meta-tegra/wiki/OE4T-Contributor-Guide)
I'll make a similar README change on meta-tegra referencing the contributor guide when this PR is merged.
> Contributor guide and pre-commit hook script

- .gitmodules
- README.md
- layers/meta-tegra-support/conf/layer.conf
- layers/meta-tegra-support/dynamic-layers/meta-mender-core/recipes-mender/mender-client/mender-client_2.4.1.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0003-Integration-of-Mender-boot-code-into-U-Boot.patch
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0010-tegra-mender-auto-configured-modified.patch
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0011-Jetson-TX2-mender-boot-commands.patch
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0012-p3541-0000_defconfig-Mender-patch.patch
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0013-Reduce-env-size-on-p3450-0000-to-64KiB.patch
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0015-Update-TX1-nano-emmc-defconfigs-for-new-UBENV-locati.patch
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_2020.07.bbappend
- layers/meta-tegrademo/classes/mender-workarounds.bbclass
- layers/meta-tegrademo/conf/distro/tegrademo-mender.conf
- layers/meta-tegrademo/conf/template-tegrademo-mender/bblayers.conf.sample
- scripts-setup/git-scripts/prepare-commit-msg
- scripts-setup/setup-git-hooks
* Switch meta-mender and meta-mender-community to upstream repos, dunfell branches
* Update other layers to gatesgarth latest
* Port fixes/workarounds from dunfell-l4t-r32.4.3
* Add bbappends to deal with dunfell <-> gatesgarth/R32.4.4 differences for meta-mender-tegra
> Layer updates for gatesgarth

- layers/meta-tegrademo/recipes-demo/packagegroups/packagegroup-demo-vulkantests.bb
which has been dropped from OE-Core.
Fixes #23
> packagegroup-demo-vulkantests: drop vulkan-demos

- scripts-setup/setup-env-internal
With the change at https://github.com/OE4T/tegra-demo-distro/commit/a5b816f2009e4a407ab7c89b793d647095347a64
we are now validating distros are available before allowing them to
be used.  This highlights a limitation with distro selection only
being allowed in predetermined directories, rather than supporting
redefining in any meta- sublayer.
Modify to support custom distros defined in proprietary layers.
Signed-off-by: Dan Walkes <danwalkes@boulderai.com>
> setup-env-internal: Support custom distro location

- layers/meta-demo-ci/classes/mirror_updates.bbclass
- layers/meta-demo-ci/conf/layer.conf
- layers/meta-demo-ci/lib/oeaws/botos3fetcher.py
- layers/meta-demo-ci/lib/oeaws/s3session.py
- layers/meta-tegrademo/conf/distro/tegrademo-mender.conf
- layers/meta-tegrademo/conf/distro/tegrademo.conf
- layers/meta-tegrademo/conf/template-tegrademo-mender/bblayers.conf.sample
- layers/meta-tegrademo/conf/template-tegrademo/bblayers.conf.sample
with a bbclass and some library modules to support the CI autobuilder in AWS.
The layer gets added to the layer set, but requires extra configuration to use; otherwise it has no effect.  The extra configuration is added as part of the autobuilder setup.
> Add meta-demo-ci layer

- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/cboot/cboot-t18x_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/cboot/cboot-t19x_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/redundant-boot-overrides/update-nvbootctrl.service.in
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/redundant-boot-overrides_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/tegra-nv-boot-control-config_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tools/setup-nv-boot-control/target-mkdir.conf
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tools/setup-nv-boot-control_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/mender-client/mender-client_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/tegra-state-scripts/tegra-state-scripts_%.bbappend
* Updates meta-tegra to pick up support for cboot reading variables created with the `tegra-bootinfo` tool
* Adds overrides for implementing changes similar to the following pending upstream changes:
* https://github.com/mendersoftware/meta-mender-community/pull/208
* Changes on https://github.com/BoulderAI/meta-mender-community/tree/dunfell%2Btests%2Bdeltaupdates
> Changes for eliminating rootfs changes during Mender updates

- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/libubootenv-fake/fw_printenv
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/libubootenv-fake_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-core/initrdscripts/tegra-minimal-init/platform-preboot-cboot.sh
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-core/initrdscripts/tegra-minimal-init_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/mender-client/mender-client_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/tegra-state-scripts/tegra-state-scripts_%.bbappend
- layers/meta-tegra-support/recipes-bsp/tegra-bup-payload/tegra-bup-payload_%.bbappend
For Mender builds, replace the tegra-redundant-boot tools from the L4T BSP with [tegra-boot-tools](https://github.com/OE4T/tegra-boot-tools):
* Update the Mender state scripts to use the new tools
* For cboot platforms, add bootcount check to initramfs and boot-success marking to normal rootfs using the utilities/services provided by tegra-boot-tools 
* Update runtime dependencies where needed to switch to the new tools
After this update:
* The `tegra-boot-control` utility replaces `nvbootctrl`.  An emulation script for `nvbootctrl` is added to handle downgrades (since the downloaded state scripts assume `nvbootctrl` is available).
*  The `tegra-bootloader-update` utility replaces `nv_update_engine` (and no `nv_update_verifier` service is installed) on cboot platforms, and replaces …
> Switch from NVIDIA bootloader tools to tegra-boot-tools

- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-nano-2gb-devkit/flash_mender.xml
- layers/meta-tegrademo/conf/distro/tegrademo-mender.conf
- layers/meta-tegrademo/recipes-core/base-files/base-files/tegrademo-mender/fstab-swap
- layers/meta-tegrademo/recipes-core/base-files/base-files_%.bbappend
This patch series fixes the build issues for `jetson-nano-2gb-devkit` machines for the tegrademo-mender distro.
A flash layout specific to the Nano-2GB is added.  It's identical to the regular Nano devkit layout, with the addition of a swap partition (NV recommends adding swap space for any AI/ML work with the Nano 2GB).  The swap space is set up via an fstab entry.
Mender settings for the target are adjusted to account for the additional partition.
> Updates for the Nano 2GB dev kit for tegrademo-mender

- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-mender/tegra-state-scripts/tegra-state-scripts_%.bbappend
for the cboot+U-Boot case, which adds a mkdir command that
is missing from the upstream copy.
> dynamic-layers/meta-mender-tegra: add fixed state script

- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-nano-2gb-devkit/flash_mender.xml
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/tegra-binaries/mender-custom-flash-layout/jetson-nano-devkit/flash_mender.xml
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/patches/0016-Update-env-for-SPIflash-Nanos-for-R32.5.0-with-Mende.patch
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
- layers/meta-tegra-support/dynamic-layers/meta-mender-tegra/recipes-bsp/u-boot/u-boot-tegra_2020.10.bbappend
- layers/meta-tegrademo/conf/distro/tegrademo-mender.conf
For Nano devkits (both 4GB and 2GB), update the layout of the SPI flash:
* Reduce the size of the LNX partition by 32KiB
* Move the UBENV partition to 0x3D0000
* Reduce the U-Boot environment size to 32KiB
* Restore the EKS and BMP partitions that were omitted during the original R32.5.0 integration
This allows us to fit all of the boot partitions and the redundant U-Boot environment areas into the SPI flash.  Since our U-Boot build is only around 640KiB in size, we still have around 60KiB of room for future growth with the smaller LNX size.  The 32KiB U-Boot environment size also provides plenty of room for growth, since our default environment is only around 6Kib.
Fixes #43
> Rework Nano U-Boot environment for Mender builds

- README.md
- layers/meta-tegrademo/conf/distro/tegrademo-mender.conf
Since uboot slot alignment issues are tricky, unless you know what
you are doing you probably want cboot as your bootloader for TX2/mender
See discussion at https://github.com/OE4T/meta-mender-community/pull/8#issuecomment-745564642
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>
> tegrademo-mender: Use cboot by default on TX2

- layers/meta-tegrademo/scripts/oe4t-tegraflash-deploy
- layers/meta-tegrademo/scripts/setup-udev-rules
Move the deploy script out of meta mender community, clean
it up to have arguments and not require running under sudo.
Move the steps from the https://github.com/OE4T/meta-tegra/wiki/Flashing-the-Jetson-Dev-Kit
page into a `setup-udev-rules` script and reference this if
deploy fails.
Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>
> scripts: Add deploy and setup udev rules script

- README.md
- layers/meta-tegrademo/conf/distro/tegrademo-mender.conf
- layers/meta-tegrademo/scripts/oe4t-tegraflash-deploy
- layers/meta-tegrademo/scripts/setup-udev-rules
Thanks for getting the repo up to date for the mender community upstream @madisongh 
There are two other changes here I was thinking we may want to backport to dunfell r32.4.3 since that's our stable mender branch.  They may make sense in r32.5.0 and/or gatesgarth too.
* I'd like to move the deploy script into the demo distro since I've removed the one I had in meta-mender-community with https://github.com/mendersoftware/meta-mender-community/pull/221
* I think we should make the `cboot-t18x` the default bootloader for the `tegrademo-mender` distro.  It's maybe not typical to put a change like this on a stable branch but since this shouldn't impact anyone's existing custom distribution and is documented clearly in the README I'd hope it would be safe.  Also we've found from experience you …
> Dunfell+oe4t deploy scripts + cboot default on R32.4.3

- layers/meta-tegrademo/classes/rootfs-postcommands-overrides.bbclass
While it's typical to use a read-only rootfs with Mender,
we shouldn't assume it, so run the replacement scriptlet
only when IMAGE_FEATURES has read-only-rootfs set.
> rootfs-postcommands-overrides: make conditional on read-only-rootfs

- layers/meta-tegrademo/recipes-bsp/u-boot/u-boot-tegra/0018-env-enable-fit-image-support-with-mender.patch
- layers/meta-tegrademo/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
> u-boot-tegra: enable FIT image support with mender

- layers/meta-tegra-support/recipes-test/eglstreams/eglstreams-kms-example_git.bb
Most other recipes use https and it is needed for downloading through company firewall.
> Add https protocol to SRC_URI of eglstreams-kms-example

- layers/meta-tegra-support/recipes-test/tegra-tests/gstreamer-tests/capturetest.sh.in
* Perform `$ git cherry-pick` using this [commit](https://github.com/OE4T/tegra-demo-distro/commit/f8a10c623d1b9b944a6c16bad1d6719fcf774a61) to fix GST capturetest script issue for `dunfell branch` (`Jetpack 4.6` / `R32.6.1`)
> gstreamer-tests: fix capturetest script issue

- layers/meta-tegra-support/recipes-test/tegra-tests/vpi1-tests/run-vpi1-tests.sh
- layers/meta-tegra-support/recipes-test/tegra-tests/vpi1-tests_1.0.bb
- layers/meta-tegrademo/conf/template-tegrademo-mender/conf-notes.txt
- layers/meta-tegrademo/conf/template-tegrademo/conf-notes.txt
- layers/meta-tegrademo/recipes-demo/images/demo-image-full.bb
* tests were done by using `Jetson TX2` 
```
root@jetson-tx2-devkit:~# run-vpi1-tests 
=== BEGIN: convolve_2d ===
...
Tests run:     27
Tests passed:  20
Tests skipped: 5
Tests failed:  2
root@jetson-tx2-devkit:~# 
```
> backport VPI tests from master to dunfell-l4t-r32.5.0 branch

- layers/meta-tegrademo/recipes-demo/packagegroups/packagegroup-demo-westontests.bb
gstreamer-tests needs x11 for nvvideosinks. Don't build it without x11 in DISTRO_FEATURES.
> westontests: only build gstreamer-tests if x11 is in DISTRO_FEATURES

- layers/meta-tegrademo/recipes-bsp/tegrademo-devicetree/tegrademo-devicetree/tegra194-p2888-0001-p2822-0000-oe4t.dts
- layers/meta-tegrademo/recipes-bsp/tegrademo-devicetree/tegrademo-devicetree/tegra194-p3668-all-p3509-0000-oe4t.dts
- layers/meta-tegrademo/recipes-bsp/tegrademo-devicetree/tegrademo-devicetree_1.0.bb
This recipe adds a couple example devicetree files to demonstrate the use of the virtual/dtb provider. To use these device trees in a build, something like the following can be added to the local.conf:
```
PREFERRED_PROVIDER_virtual/dtb = "tegrademo-devicetree"
DTBFILE:jetson-xavier-nx-devkit = "tegra194-p3668-all-p3509-0000-oe4t.dtb"
DTBFILE:jetson-xavier-nx-devkit-emmc = "tegra194-p3668-all-p3509-0000-oe4t.dtb"
DTBFILE:jetson-agx-xavier-devkit = "tegra194-p2888-0001-p2822-0000-oe4t.dtb"
```
---
Note that in order to build this, the changes from https://github.com/OE4T/linux-tegra-5.10/pull/3 are required, at least as far as I could tell. If there is a better way to handle this, please let me know.
> meta-tegrademo: add tegrademo-devicetree recipes

- scripts-setup/create-distro-layer
The previous implementation assumed `REQUIRED_TD_BBLAYERS_CONF_VERSION` was the same between the base distro and the mender distro script.
Instead of attempting to patch the distro.conf file with tegrademo-mender content, use the tegrademo-mender content as-is.
Then tweak the copy scripts in the mender case to avoid replacing the tegrademo.conf reference in the distro configuration copied from the mender config.  Use the name `${DISTRO_NAME}-base.conf` for the file created from `tegrademo.conf` to avoid
name collisions with the later rename scripts.
Tested with
```
./scripts-setup/create-distro-layer -d my-mender -m
. ./setup-env -m jetson-nano-devkit-emmc -d my-mender build-my-mender
```
and
```
./scripts-setup/create-distro-layer -d my-distro
. ./setup-env -m jetson-nano-devkit-emmc -d …
```
> scripts: Fix create-distro-layer mender option

- layers/meta-demo-ci/lib/oeaws/s3session.py
Corrects a typo found when sso credentials expired before uploads occurred.
> Fix s3retry_wait typo

- layers/meta-tegrademo/conf/distro/include/tegrademo.inc
- layers/meta-tegrademo/conf/distro/tegrademo.conf
The current state of the tegrademo.conf distribution configuration file takes a couple of assumptions on the environment it will be used in. The primary one is using the setup-env.sh script from the tegra-demo-distro repository,  which means bblayers.conf has to be set up. This breaks other build flows and makes it hard for other distribution configurations to derive from tegrademo. By moving the setup agnostic parts (e.g. the ones defining the ABI/API) into an include file, they can be easily used as a base for customized distributions.
Changelog: Title
Ticket: None
> feat: tegrademo.conf: move setup-independent parts into include

- layers/meta-demo-ci/classes/mirror_updates.bbclass
- layers/meta-demo-ci/lib/oeaws/aws_env.py
- layers/meta-demo-ci/lib/oeaws/botos3fetcher.py
AWS credentials can be provided in environment variables in order for s3Session to access a private bucket.
When credentials are set as environment variables and passed with `BB_ENV_EXTRAWHITE` (or `BB_ENV_PASSTHROUGH_ADDITIONS`) they are not taken into account and do not appear in environment when  `downloads_mirror_update` or `sstate_mirror_update` are called.
This commit move the `fix_env` function from `botos3fetcher.py` into a dedicated file in order to be used in both `botos3fetcher.py` and `mirror_updates.bbclass`
> mirror_update.bbclass: add fix environment function to get AWS credentials

- scripts-setup/setup-env-internal
Fixes the following warning:
```
egrep: warning: egrep is obsolescent; using grep -E
```
> setup-env-internal: replace egrep as it is obsolescent

- layers/meta-tegrademo/conf/distro/include/tegrademo.inc
* Update meta-tegra repo to latest supporting [1].
* Set distro configuration to default to A/B redundant rootfs.
1: https://github.com/OE4T/meta-tegra/pull/1428
> tegrademo: Update to use A/B Rootfs by default

- layers/meta-tegra-support/classes/tegra-support-sanity.bbclass
When the templates was moved because of changes to OE-Core master, the path here was missed, and not updated.
> tegra-support-sanity: fix templates path

- layers/meta-tegrademo/scripts/setup-udev-rules
The list can be found in the quickstart guide.
https://docs.nvidia.com/jetson/archives/r36.2/DeveloperGuide/IN/QuickStart.html#to-determine-whether-the-developer-kit-is-in-force-recovery-mode
> setup-udev-rules: add orin product ID's

- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-demo/images/swupdate-image-tegra.bb
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-demo/images/swupdate-image-tegra/sw-description
* Fix dependencies for dtbfile reference
* Update the path to the capsule file to match JP6
* Remove overrides no longer used on jp6 branches.
These commits should be ready for backport to `scarthgap` as well.
The first two commits can also go to `scarthgap-l4t-r35.x` (keep the overrides for t194 there)
FYI the master build is broken until https://groups.google.com/g/swupdate/c/U-GNI3mhbX0 or something similar is merged in meta-swupdate.  I've tested locally with these changes on `jetson-orin-nano-devkit-nvme` in these scenarios:
1) master branch to master branch (Jetpack 6)
2) kirkstone branch to master branch (Jetpack 5->6).
> swupdate fixes for master

- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-demo/images/swupdate-image-tegra.bb
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-demo/images/swupdate-image-tegra/sw-description
Backport of https://github.com/OE4T/tegra-demo-distro/pull/305 to scarthgap, in an attempt to resolve https://github.com/OE4T/tegra-demo-distro/issues/303
I left out https://github.com/OE4T/tegra-demo-distro/pull/305/commits/cf54e8924fdc6de733e9a28af9af20834d998990 and kept tegra194 references for the time being since based on discussion in last month's meeting it may be possible for tegra194 to ultimately be supported on Jetpack 6 through the community layer.
> swupdate: scarthgap fixes

- layers/meta-tegrademo/conf/kas/include/tegra-demo-distro-branch.yml
- layers/meta-tegrademo/conf/kas/tegra-demo-distro.yml
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/README.md
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/conf/kas/include/swupdate-base.yml
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/conf/kas/include/tegra-demo-distro-swupdate-lasttested.yml
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/conf/kas/swupdate-oe4t-lasttested.yml
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/conf/kas/swupdate-oe4t.yml
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/scripts/build-jetson-orin-nano-devkit-nvme.sh
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/scripts/kasbuildbase.sh
This is the PR I've discussed for the past few monthly meetings.  It sets up a way to build the swupdate demo with either floating or fixed branches and an alternative to the setup-env script for building the demo distro.
It also provides an underlying `tegra-demo-distro.yml` configuration to build the demo distro standalone without swupdate, with command line like `kas build layers/meta-tegrademo/conf/kas/tegra-demo-distro.yml`.  Projects in this or other repositories can extend `demo-image-base` or other recipes in this repo by including this config file in their kas configuration and without the need to fork this entire repo.
Full list of changes:
* Add a base tegra-demo-distro kas config as an alternative to using the setup-env option currently supported.
* Use the defaults setting in …
> swupdate: add kas configurations

- layers/meta-tegrademo/dynamic-layers/meta-swupdate/conf/kas/swupdate-oe4t.yml
Fix ordering on swupdate-oe4t.yml to ensure the swupdate includes happen after the tegrademo includes.
Without this the target used by tegrademo base includes overrides the swupdate-tegra target and the swupdate .swu file is not built as a part of the build process.
> swupdate: fix build target

- layers/meta-tegrademo/conf/layer.conf
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/README.md
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/classes-recipe/tegra_swupdate.bbclass
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-demo/images/swupdate-image-tegra.bb
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-demo/images/swupdate-image-tegra/bootloader-update.lua
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-demo/images/swupdate-image-tegra/sw-description
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-support/swupdate/swupdate-machine-config/swupdate-genconfig.sh.in
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-support/swupdate/swupdate-machine-config_1.0.bb
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-support/swupdate/tegra-swupdate-script/tegra-swupdate-script.lua.in
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-support/swupdate/tegra-swupdate-script_1.0.bb
As previously discussed since capsule update durations can be long on some platforms it may be beneficial to avoid capsule updates when the bootloader version does not change.
swupdate has a nice feature for this with [install-if-different](https://sbabic.github.io/swupdate/sw-description.html#checking-version-of-installed-software)
This PR adds a configuration feature for the swupdate demo `TEGRA_SWUPDATE_BOOTLOADER_INSTALL_ONLY_IF_DIFFERENT`, defaulted to 'false' which when changed to `true` in local.conf or distro.conf, modifies to only switch the rootfs when the L4T version has not changed between the currently installed bootloader and the on-target bootloader, thereby speeding up the update process and avoiding the unnecessary bootloader capsule update.
* add tegra_swupdate.bbclass …
> swupdate: install-if-different bootloader support

- layers/meta-tegrademo/conf/kas/tegra-demo-distro.yml
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/README.md
- layers/meta-tegrademo/dynamic-layers/meta-swupdate/scripts/kasbuildbase.sh
With this commit I believe I now have a kas setup which will work either with build scripts inside this repo (such as the swupdate demo) and cloning building using the layout used for this repo or in scripts outside this repo, as demonstrated and tested on https://github.com/Trellis-Logic/kas-demos.
I've also optimized the getting started experience for someone deploying the kas instructions on the swupdate demo layer here.
* Fix relative paths to work with external kas includes
* Fix local path references to work with external kas includes
* Update swupdate README kas instructions to recommend shallow clones, since kas will update the subdirs as needed.
* Update base build script to run update with nofetch and shallow clone options, since we only need to ensure the submodule dirs are …
> kas: fix paths to support external repos

- layers/meta-tegrademo/dynamic-layers/meta-swupdate/recipes-demo/images/swupdate-image-tegra.bb
Based on observations in [1] and [2], the inclusion of sysroots
for DTB depends can cause dependency issues during builds when
using rm_work.  The underlying cause of this may be a bug in
openembedded somewhere, but it's not obvious where.
We don't need the full sysroot for these targets, however, so
instead of using the do_populate_sysroot target set by tegra_dtb_extra_deps,
just use the do_deploy target for these packages instead. This
does not match what is typically done for image dependencies by swupdate in [3],
however see discussion in [4] for the rationale.
This puts the relevant DTB files in the deploy directory where we can access
them when building the swu file.
In addition, clean up the recipe for the update image to keep
non image recipes out of IMAGE_DEPENDS and instead add …
> swupdate: fix do_swuimage DTB depends
